name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '0 8 * * *' 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Supabase Client
      - name: Install Supabase Client
        run: npm install @supabase/supabase-js --force

      # Step 4: Ping Supabase
      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.NEXT_SERVICE_ROLE_KEY }}
        run: |
          node -e "
          (async () => {
            try {
              const { createClient } = require('@supabase/supabase-js');
              const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

              // Inserisce un nuovo ping nella tabella ping_log
              const { data, error } = await supabase
                .from('ping_log')
                .insert([{ ping_time: new Date().toISOString() }]);

              if (error) throw error;

              console.log('Ping registrato con successo ✅', data);
            } catch (err) {
              console.error('Errore ping Supabase ❌', err.message);
              process.exit(1);
            }
          })();
          "

